# Carolina Tapia  tarea Final Curso DevOps
name: TareaFinal

# con el push cada vez que se actualiza opera el yml
on: 
  push:

# Sistema Operativa
jobs:
  build:
    runs-on: ubuntu-latest
    # Actions comienza checkout 
    steps:
    - uses: actions/checkout@v3
    # Version Java de app 
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
       java-version: '11'
       distribution: 'temurin'
    # Construye y valida con gradlew 
    -  name: Build with Gradle
       run: |
        chmod +x gradlew
        ./gradlew clean :service-a:build

   # Me da error en la integracion con SonarCloud
   # - name: SonarCloud Scan
   #   uses: cbtapiac/devops_tareaFinal@master
   #   env:
   #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
   #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    # conexion de docker , pero falla la conexion :(   
    - name: Docker Login
      uses: docker/login-action@v2.2.0
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
    # construye docker 
    - name: Docker Build
      run: |
          docker build --tag cbtapiac/devops_tareafinal:latest .
          docker images
    # hace el push al docker    
    - name: Docker Push
      run:
        docker push  cbtapiac/devops_tareafinal
  # deploy 
  deploy:
      needs: build
      runs-on: self-hosted
      steps:

      - name: checkout
        uses: actions/checkout@v3.5.3
  

