name: TareaFinal


on: 
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
       java-version: '11'
       distribution: 'temurin'

    #- name: Build with Gradle
      #run:
      # chmod +x gradlew
      # ./gradlew build

   # - name: Analisis SonarCloud
      #  chmod +x gradlew
       # ./gradlew build sonar - Dsonar.token=${{} secrets.TOKEN_SONARCLOUD}
       
    - name: Docker Login 
      uses: docker/login-action@v2.2.0
      with:
        username: ${{ secrets.DOCKER_USERNAME}}
        password: ${{ secrets.DOCKER_PASSWORD}}

    - name: Docker Build
      run: 
           docker build --tag cbtapiac/devops_tareaFinal:latest
           docker images
         
    - name: Docker Push
      run:
         docker push  cbtapiac/devops_tareaFinal
  
  deploy:
      needs: build
      runs-on: self-hosted
      steps:

      - name: checkout
        uses: actions/checkout@v3.5.3

      - name: Deploy Kubernetes
        run:
           docker pull cbtapiac/devops_tareaFinal
           docker run -d -p 8081:8080 -e spring.profiles.active=prod -e serviceb.url=http://localhost:8082 -e servicec.url=http://localhost:8083 narramadan/spring-multi-module-service-service-a

