name: TareaFinal


on: 
  push:

jobs:
  build:
    runs-on: ubuntu-latest
     
    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
       java-version: '11'
       distribution: 'temurin'

    - name: Build with Gradle
      run:
        #chmod +x gradle
        gradle build :service-a:bootBuildImage
       #././gradlew clean :service-a:build

   # - name: Analisis SonarCloud
      #  chmod +x gradlew
       # ./gradlew build sonar - Dsonar.token=${{} secrets.TOKEN_SONARCLOUD}
